version: "3.8"
services:
  app:
    ports:
      - "5000:5000"
    environment: 
      - "SERVER_PORT=5000"
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_USER=postgres"
      - "DB_PASSWORD=pass"
      - "DB_NAME=voting"
      - "DB_DRIVER=postgres"
      - "BROKER_CONN_STRING=tcp://broker:1883"
    build:
      context: .
      dockerfile: ./builds/Dockerfile
    depends_on: 
      - db
      - broker
  db:
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - "POSTGRES_PASSWORD=pass"
      - "POSTGRES_DB=voting"
  broker:
    image: "emqx/emqx:latest"
    restart: always
    ports:
      - "1883:1883"
      - "18083:18083"
  test-runner:
    image: "peterevans/vegeta"
    depends_on: 
      - app
    command: >-      
      sh -c "echo 'GET http://app:5000/agenda/{agendaID}/session/{sessionID}/result'
      | vegeta attack -rate=2000 -duration=10s 
      | tee results.bin 
      | vegeta report"